version: "3.9"

services:
  lixianjun.info:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/www
      - ./log:/www/log
